trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseJavaVersion@0
  inputs:
    versionSpec: '8'  # Use the appropriate Java version

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Add steps for additional tasks as needed, e.g., code analysis, deployment, etc.
